/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package effectiveJava;

import effectiveJava.Plant.Genus;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Ivy ivy = (Ivy) Plant.of(Genus.IVY);
        System.out.println(ivy.getName());
        System.out.println(ivy.getVineColor());

        Jade jade = (Jade) Plant.of(Genus.JADE);
        System.out.println(jade.getName());
        System.out.println(jade.getContainer());
    }
}
